version: '3.3'

services:
  web:
    build:
      context: .
    container_name: coding-block
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped
    command: ["bash", "-c", "cron && rails server -b 0.0.0.0"]
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coding_block_backend_development
      DATABASE_URL: postgres://postgres:password@db:5432/coding_block_backend_development

  db:
    image: postgres:16
    container_name: postgres_16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coding_block_backend_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
